.class public Laoc/kingdoms/lukasz/jakowski/GameValues$GameValue_Diplomacy;
.super Ljava/lang/Object;
.source "GameValues.java"


# annotations
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Laoc/kingdoms/lukasz/jakowski/GameValues;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x9
    name = "GameValue_Diplomacy"
.end annotation


# instance fields
.field public ALLIANCE_SCORE_AT_WAR:F

.field public ALLIANCE_SCORE_BASE_RANK_SCORE_MAX:F

.field public ALLIANCE_SCORE_BASE_RANK_SCORE_MIN:F

.field public ALLIANCE_SCORE_BASE_VALUE:F

.field public ALLIANCE_SCORE_DIFFERENT_GOVERNMENT:F

.field public ALLIANCE_SCORE_DIFFERENT_GOVERNMENT_GROUP:F

.field public ALLIANCE_SCORE_DIFFERENT_RELIGION:F

.field public ALLIANCE_SCORE_DIFFERENT_RELIGION_GROUP:F

.field public ALLIANCE_SCORE_DISTANCE:F

.field public ALLIANCE_SCORE_FOR_VASSAL_OF_CIV:F

.field public ALLIANCE_SCORE_MAX_NUM_OF_ALLIANCES:I

.field public ALLIANCE_SCORE_PER_AGGRESSIVE_EXPANSION:F

.field public ALLIANCE_SCORE_PER_RELATION:F

.field public ALLIANCE_SCORE_PER_SAME_RIVAL:F

.field public ALLIANCE_SCORE_RIVALS:F

.field public BASE_MAX_NUM_OF_ALLIANCES:I

.field public CALL_TO_ARMS_REFUSE_LEGACY:F

.field public DEFENSIVE_PACT_SCORE_AT_WAR:F

.field public DEFENSIVE_PACT_SCORE_BASE_RANK_SCORE_MAX:F

.field public DEFENSIVE_PACT_SCORE_BASE_RANK_SCORE_MIN:F

.field public DEFENSIVE_PACT_SCORE_BASE_VALUE:F

.field public DEFENSIVE_PACT_SCORE_DIFFERENT_GOVERNMENT:F

.field public DEFENSIVE_PACT_SCORE_DIFFERENT_GOVERNMENT_GROUP:F

.field public DEFENSIVE_PACT_SCORE_DIFFERENT_RELIGION:F

.field public DEFENSIVE_PACT_SCORE_DIFFERENT_RELIGION_GROUP:F

.field public DEFENSIVE_PACT_SCORE_DISTANCE:F

.field public DEFENSIVE_PACT_SCORE_PER_AGGRESSIVE_EXPANSION:F

.field public DEFENSIVE_PACT_SCORE_PER_DEFENSIVE_PACT:F

.field public DEFENSIVE_PACT_SCORE_PER_RELATION:F

.field public DEFENSIVE_PACT_SCORE_PER_SAME_RIVAL:F

.field public DEFENSIVE_PACT_SCORE_RIVALS:F

.field public DIPLOMACY_ALLIANCE_COST:F

.field public DIPLOMACY_ALLIANCE_EXPIRES:I

.field public DIPLOMACY_ALLIANCE_EXPIRES_EXTRA_RANDOM:I

.field public DIPLOMACY_DAMAGE_RELATIONS_COST_PER_MONTH:F

.field public DIPLOMACY_DAMAGE_RELATIONS_MAX:F

.field public DIPLOMACY_DAMAGE_RELATIONS_TIME:I

.field public DIPLOMACY_DAMAGE_RELATIONS_VALUE:F

.field public DIPLOMACY_DECLARE_WAR_COST:F

.field public DIPLOMACY_DECLARE_WAR_LOW_MANPOWER_INFO_IF_BELOW:F

.field public DIPLOMACY_DEFENSIVE_PACT_COST:F

.field public DIPLOMACY_DEFENSIVE_PACT_EXPIRES:I

.field public DIPLOMACY_DEMAND_MILITARY_ACCESS_COST:F

.field public DIPLOMACY_FRIENDLY_LIMIT_IN_DIPLOMACY_VIEW:I

.field public DIPLOMACY_GIFT_COST:F

.field public DIPLOMACY_GIFT_GOLD_PER_CLICK:F

.field public DIPLOMACY_GIFT_MAX_CLICKS:I

.field public DIPLOMACY_GIFT_REFUSE_MULTIPLE:F

.field public DIPLOMACY_GIFT_RELATION_PER_CLICK:F

.field public DIPLOMACY_GUARANTEE_COST:F

.field public DIPLOMACY_GUARANTEE_EXPIRES:I

.field public DIPLOMACY_IMPROVE_RELATIONS_COST_PER_MONTH:F

.field public DIPLOMACY_IMPROVE_RELATIONS_MAX:F

.field public DIPLOMACY_IMPROVE_RELATIONS_TIME:I

.field public DIPLOMACY_IMPROVE_RELATIONS_VALUE:F

.field public DIPLOMACY_IMPROVE_RELATIONS_VALUE_PRESTIGE:F

.field public DIPLOMACY_MESSAGE_DAYS:I

.field public DIPLOMACY_MESSAGE_RELATIONS_DAYS:I

.field public DIPLOMACY_MILITARY_ACCESS_EXPIRES:I

.field public DIPLOMACY_NON_AGGRESSION_PACT_COST:F

.field public DIPLOMACY_NON_AGGRESSION_PACT_EXPIRES:I

.field public DIPLOMACY_OFFER_MILITARY_ACCESS_COST:F

.field public DIPLOMACY_POINTS_MAX:I

.field public DIPLOMACY_POINTS_MAX_PER_PROVINCE:F

.field public DIPLOMACY_POINTS_MIN:I

.field public DIPLOMACY_POINTS_PER_MONTH_BASE_VALUE:F

.field public DIPLOMACY_POINTS_RANK_BLACK:F

.field public DIPLOMACY_POINTS_RANK_BRONZE:F

.field public DIPLOMACY_POINTS_RANK_GOLD:F

.field public DIPLOMACY_POINTS_RANK_SILVER:F

.field public DIPLOMACY_REFUSE_ALLIANCE_OPINION_CHANGE_TO:F

.field public DIPLOMACY_RELATIONS_FRIENDLY:F

.field public DIPLOMACY_RELATIONS_MAX:F

.field public DIPLOMACY_RELATIONS_MIN:F

.field public DIPLOMACY_RELATIONS_WAR_EXTRA:I

.field public DIPLOMACY_RELATION_COOPERATIVE:F

.field public DIPLOMACY_RELATION_DETACHED:F

.field public DIPLOMACY_RELATION_NEUTRAL:F

.field public DIPLOMACY_RELATION_STRAINED:F

.field public DIPLOMACY_RELATION_UNFAVORABLE:F

.field public DIPLOMACY_RELATION_WARM:F

.field public DIPLOMACY_SEND_AN_INSULT_COST_LEGACY:F

.field public DIPLOMACY_SEND_AN_INSULT_DAMAGE:F

.field public DIPLOMACY_SEND_INSULT_COST:F

.field public DIPLOMACY_TRUCE_EXPIRES:I

.field public DIPLOMACY_VIEW_BIGGEST_CITIES_LINES_MAX:I

.field public DIPLOMACY_VIEW_BIGGEST_CITIES_LINES_MIN:I

.field public DIPLOMACY_VIEW_BIGGEST_CITIES_LINES_PERC_OF_PROVINCES:F

.field public INTERVENE_IN_WAR_IMPROVE_RELATIONS_VALUE:F

.field public NON_AGGRESSION_SCORE_AT_WAR:F

.field public NON_AGGRESSION_SCORE_BASE_RANK_SCORE_MAX:F

.field public NON_AGGRESSION_SCORE_BASE_RANK_SCORE_MIN:F

.field public NON_AGGRESSION_SCORE_BASE_VALUE:F

.field public NON_AGGRESSION_SCORE_DIFFERENT_GOVERNMENT:F

.field public NON_AGGRESSION_SCORE_DIFFERENT_GOVERNMENT_GROUP:F

.field public NON_AGGRESSION_SCORE_DIFFERENT_RELIGION:F

.field public NON_AGGRESSION_SCORE_DIFFERENT_RELIGION_GROUP:F

.field public NON_AGGRESSION_SCORE_DISTANCE:F

.field public NON_AGGRESSION_SCORE_PER_NON_AGGRESSION_PACTS:F

.field public NON_AGGRESSION_SCORE_PER_RELATION:F

.field public NON_AGGRESSION_SCORE_PER_SAME_RIVAL:F

.field public NON_AGGRESSION_SCORE_RIVALS:F

.field public RANDOM_RELATIONS_DISTANCE:F

.field public RELATIONS_CHANGE_PER_UPDATE_TO_NEUTRAL:F

.field public SELL_PROVINCE_GOLD_PER_PROVINCE_VALUE:F

.field public SHARE_TECHNOLOGY_OPINION:F

.field public SHOW_LIST_OF_CIVS_RELATIONS_IN_PLAYERS_CIV_VIEW:Z

.field public STARTING_DIPLOMACY_POINTS:F

.field public STARTING_RANDOM_RELATIONS:I

.field public STARTING_RANDOM_RELATIONS_CHANCE:I

.field public STARTING_RANDOM_RELATIONS_MIN:I


# direct methods
.method public constructor <init>()V
    .registers 1

    .line 1605
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
