import io
p = '/tmp/w3/smali/aoc/kingdoms/lukasz/map/province/ProvinceDrawArmy.smali'
lines = io.open(p, encoding='utf-8').read().split('\n')
m_start = None
for i, l in enumerate(lines):
    if '.method public static final drawAirForceRadarIcons' in l:
        m_start = i
        break
assert m_start is not None
ins = None
for i in range(m_start, m_start + 200):
    if 'getAirDrawPosY(IF)I' in lines[i]:
        for k in range(i+1, min(i+8, len(lines))):
            if 'move-result v5' in lines[k]:
                ins = k
                break
        break
assert ins is not None
print('insert after line', ins + 1)

block = [
    '',
    '    # ===== R3b: radar building range circles =====',
    '    invoke-virtual {v2}, Laoc/kingdoms/lukasz/map/province/Province;->getCenterY_Real()I',
    '    move-result v6',
    '    int-to-float v6, v6',
    '    const v7, 0x45866000    # 4300.0f',
    '    sub-float v6, v6, v7',
    '    div-float v6, v6, v7',
    '    const v7, 0x3fc90fdb',
    '    mul-float v6, v6, v7',
    '    float-to-double v6, v6',
    '    invoke-static {v6, v7}, Ljava/lang/Math;->cos(D)D',
    '    move-result-wide v6',
    '    double-to-float v6, v6',
    '    const/high16 v7, 0x3f800000    # 1.0f',
    '    cmpl-float v9, v6, v7',
    '    if-lez v9, :r3b_c1',
    '    move v6, v7',
    '    :r3b_c1',
    '    const/high16 v7, 0x3e800000    # 0.25f',
    '    cmpl-float v9, v6, v7',
    '    if-gez v9, :r3b_c2',
    '    move v6, v7',
    '    :r3b_c2',
    '    # --- RADAR (300km) ---',
    '    invoke-static {}, Laoc/kingdoms/lukasz/map/battles/AirForceManager;->getInstance()Laoc/kingdoms/lukasz/map/battles/AirForceManager;',
    '    move-result-object v7',
    '    invoke-virtual {v7, v1}, Laoc/kingdoms/lukasz/map/battles/AirForceManager;->hasRadarBuilding(I)Z',
    '    move-result v7',
    '    if-eqz v7, :r3b_lw',
    '    const-string v8, "RADAR"',
    '    invoke-static {v8}, Laoc/kingdoms/lukasz/map/battles/RadarDataManager;->getRange(Ljava/lang/String;)F',
    '    move-result v7',
    '    mul-float v7, v7, v3',
    '    mul-float v14, v6, v7',
    '    float-to-int v14, v14',
    '    float-to-int v7, v7',
    '    sget v8, Laoc/kingdoms/lukasz/textures/Images;->radarFill:I',
    '    invoke-static {v8}, Laoc/kingdoms/lukasz/textures/ImageManager;->getImage(I)Laoc/kingdoms/lukasz/textures/Image;',
    '    move-result-object v8',
    '    const/high16 v10, 0x3f800000    # 1.0f',
    '    const/high16 v11, 0x3f800000    # 1.0f',
    '    const/high16 v12, 0x3f800000    # 1.0f',
    '    const v13, 0x3f800000    # 1.0f',
    '    invoke-virtual {p0, v10, v11, v12, v13}, Lcom/badlogic/gdx/graphics/g2d/SpriteBatch;->setColor(FFFF)V',
    '    move-object v9, p0',
    '    sub-int v10, v4, v7',
    '    sub-int v11, v5, v14',
    '    shl-int/lit8 v12, v7, 0x1',
    '    shl-int/lit8 v13, v14, 0x1',
    '    invoke-virtual/range {v8 .. v13}, Laoc/kingdoms/lukasz/textures/Image;->draw(Lcom/badlogic/gdx/graphics/g2d/SpriteBatch;IIII)V',
    '    :r3b_lw',
    '    # --- MIDCOURSE_ABM (400km) ---',
    '    invoke-static {}, Laoc/kingdoms/lukasz/map/battles/AirForceManager;->getInstance()Laoc/kingdoms/lukasz/map/battles/AirForceManager;',
    '    move-result-object v7',
    '    invoke-virtual {v7, v1}, Laoc/kingdoms/lukasz/map/battles/AirForceManager;->hasLongWaveRadarBuilding(I)Z',
    '    move-result v7',
    '    if-eqz v7, :r3b_aa',
    '    const-string v8, "MIDCOURSE_ABM"',
    '    invoke-static {v8}, Laoc/kingdoms/lukasz/map/battles/RadarDataManager;->getRange(Ljava/lang/String;)F',
    '    move-result v7',
    '    mul-float v7, v7, v3',
    '    mul-float v14, v6, v7',
    '    float-to-int v14, v14',
    '    float-to-int v7, v7',
    '    sget v8, Laoc/kingdoms/lukasz/textures/Images;->radarFill:I',
    '    invoke-static {v8}, Laoc/kingdoms/lukasz/textures/ImageManager;->getImage(I)Laoc/kingdoms/lukasz/textures/Image;',
    '    move-result-object v8',
    '    const/high16 v10, 0x3f800000    # 1.0f',
    '    const/high16 v11, 0x3f800000    # 1.0f',
    '    const/high16 v12, 0x3f800000    # 1.0f',
    '    const v13, 0x3f800000    # 1.0f',
    '    invoke-virtual {p0, v10, v11, v12, v13}, Lcom/badlogic/gdx/graphics/g2d/SpriteBatch;->setColor(FFFF)V',
    '    move-object v9, p0',
    '    sub-int v10, v4, v7',
    '    sub-int v11, v5, v14',
    '    shl-int/lit8 v12, v7, 0x1',
    '    shl-int/lit8 v13, v14, 0x1',
    '    invoke-virtual/range {v8 .. v13}, Laoc/kingdoms/lukasz/textures/Image;->draw(Lcom/badlogic/gdx/graphics/g2d/SpriteBatch;IIII)V',
    '    :r3b_aa',
    '    # --- ABM_SITE (150km) ---',
    '    invoke-static {}, Laoc/kingdoms/lukasz/map/battles/AirForceManager;->getInstance()Laoc/kingdoms/lukasz/map/battles/AirForceManager;',
    '    move-result-object v7',
    '    invoke-virtual {v7, v1}, Laoc/kingdoms/lukasz/map/battles/AirForceManager;->hasAAABuilding(I)Z',
    '    move-result v7',
    '    if-eqz v7, :r3b_end',
    '    const-string v8, "ABM_SITE"',
    '    invoke-static {v8}, Laoc/kingdoms/lukasz/map/battles/RadarDataManager;->getRange(Ljava/lang/String;)F',
    '    move-result v7',
    '    mul-float v7, v7, v3',
    '    mul-float v14, v6, v7',
    '    float-to-int v14, v14',
    '    float-to-int v7, v7',
    '    sget v8, Laoc/kingdoms/lukasz/textures/Images;->radarFill:I',
    '    invoke-static {v8}, Laoc/kingdoms/lukasz/textures/ImageManager;->getImage(I)Laoc/kingdoms/lukasz/textures/Image;',
    '    move-result-object v8',
    '    const/high16 v10, 0x3f800000    # 1.0f',
    '    const/high16 v11, 0x3f800000    # 1.0f',
    '    const/high16 v12, 0x3f800000    # 1.0f',
    '    const v13, 0x3f800000    # 1.0f',
    '    invoke-virtual {p0, v10, v11, v12, v13}, Lcom/badlogic/gdx/graphics/g2d/SpriteBatch;->setColor(FFFF)V',
    '    move-object v9, p0',
    '    sub-int v10, v4, v7',
    '    sub-int v11, v5, v14',
    '    shl-int/lit8 v12, v7, 0x1',
    '    shl-int/lit8 v13, v14, 0x1',
    '    invoke-virtual/range {v8 .. v13}, Laoc/kingdoms/lukasz/textures/Image;->draw(Lcom/badlogic/gdx/graphics/g2d/SpriteBatch;IIII)V',
    '    :r3b_end',
    '',
]
lines[ins + 1:ins + 1] = block
io.open(p, 'w', encoding='utf-8').write('\n'.join(lines))
print('OK inserted, new line count =', len(lines))